### ISSUE TITLE
Issue with docker compose GW building

### ISSUE THREAD

**Issue by 2dadsgn** [chirpstack/chirpstack-gateway-bridge#215]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-gateway-bridge) of this repository and believe that this is not a duplicate.

## What happened?
when ever i try to build the container for the gateway bridge in docker compose i get the error like shown below.

the problem seems to be with these lines in the make file from the dev-requirements:

dev-requirements:
	go install github.com/golang/lint/blob/6edffad5e616/golint/golint.go
	go install github.com/goreleaser/goreleaser
	go install github.com/goreleaser/nfpm

## What did you expect?
I was expecting  the container to be built like the others.

## Steps to reproduce this issue

Steps:

1.
2.
3.
4.

## Could you share your log output?

```shell

 => ERROR [chirpstack-v4-custom-chirpstack-gateway-bridge 7/7] RUN make d  3.7s
 => CANCELED [chirpstack-v4-custom-chirpstack-rest-api 3/9] RUN git clone  0.5s
------
 > [chirpstack-v4-custom-chirpstack-gateway-bridge 7/7] RUN make dev-requirements:
#0 0.364 fatal: not a git repository (or any of the parent directories): .git
#0 0.365 go install github.com/golang/lint/blob/6edffad5e616/golint/golint.go
#0 3.457 no required module provides package github.com/golang/lint/blob/6edffad5e616/golint/golint.go; to add it:
#0 3.457 	go get github.com/golang/lint/blob/6edffad5e616/golint/golint.go
#0 3.459 make: *** [Makefile:34: dev-requirements] Error 1
------
failed to solve: executor failed running [/bin/sh -c make dev-requirements]: exit code: 2


```

## Your Environment

mac os using docker compose

| Component           | Version |
| --------------------| ------- |
| Application Server  | v?.?.?  |
| Network Server      |    latest     |
| Gateway Bridge      |      latest   |
| Chirpstack API      |         |
| Geolocation         |         |
| Concentratord       |         |

**Comment by brocaar** [comment]
> fatal: not a git repository (or any of the parent directories): .git

It looks like the directory is not a `git clone`. Maybe you downloaded the `.tar.gz` source instead of a `git clone` or you are not exposing the `.git` directory to the container?
